INSERT INTO POST(ID, TITLE, BODY) VALUES (23, 'Title 1', 'Body 1');
INSERT INTO POST(ID, TITLE, BODY) VALUES (24, 'Title 2', 'Body 2');
INSERT INTO POST(ID, TITLE, BODY) VALUES (25, 'Title 3', 'Body 3');